INSERT INTO rx_examples.comunidad_autonoma (ca_id,nombre)
VALUES
	(1,'Andalucía'),
	(2,'Aragón'),
	(3,'Asturias'),
	(4,'Balears, Illes'),
	(5,'Canarias'),
	(6,'Cantabria'),
	(7,'Castilla y León'),
	(8,'Castilla - La Mancha'),
	(9,'Catalunya'),
	(18,'Ceuta'),
	(11,'Extremadura'),
	(12,'Galicia'),
	(13,'Madrid'),
	(19,'Melilla'),
	(14,'Murcia'),
	(15,'Navarra'),
	(16,'País Vasco'),
	(17,'Rioja, La'),
	(10,'Valencia');